[package]
name = "lila-push"
version = "1.0.0"
publish = false
description = "Web push microservice for lichess.org"
repository = "https://github.com/lichess-org/lila-push"
readme = "README.md"
license = "AGPL-3.0+"
authors = ["Niklas Fiekas <niklas.fiekas@backscattering.de>"]
keywords = ["web-push", "vapid", "lichess"]
edition = "2021"

[dependencies]
axum = "0.4"
tokio = { version = "1", features = ["full"] }
clap = { version = "3", features = ["derive"] }
web-push = { version = "0.9", features = ["hyper-client"], default-features = false }
serde = { version = "1", features = ["derive"] }
openssl = { version = "0.10", features = ["vendored"] }
